name: Test and check version
on:
  pull_request:
    branches:
      - main
    paths:
      - "psn_fetcher/**"
      - ".github/workflows/psn-fetcher-*.yml"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  check-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: psn_fetcher
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get version
        id: get-version
        uses: ./.github/actions/get-version
        with:
          service_name: psn-fetcher

      - name: Compare versions
        run: |
          git fetch origin main
          OLD_VERSION=$(git show origin/main:psn_fetcher/package.json 2>/dev/null | jq -r '.version' || echo "0.0.0")
          NEW_VERSION=${{ steps.get-version.outputs.version }}

          echo "OLD_VERSION=$OLD_VERSION"
          echo "NEW_VERSION=$NEW_VERSION"

          if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
            echo "❌ You must bump version in package.json for this PR"
            exit 1
          fi

          echo "✅ Version bumped."

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: psn_fetcher
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: psn_fetcher/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
